/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-22 00:33:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.LinkedList;
import uk.ac.ucl.model.TodoList;
import java.util.ArrayList;
import uk.ac.ucl.model.Item;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("uk.ac.ucl.model.Item");
    _jspx_imports_classes.add("uk.ac.ucl.model.TodoList");
    _jspx_imports_classes.add("java.util.LinkedList");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("    <title>");
      out.print((String) request.getAttribute("listName"));
      out.write("</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("<div class=\"main\">\n");
      out.write("\n");
      out.write("    <form method=\"POST\" action=\"/runsearch.html\">\n");
      out.write("        <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" />\n");
      out.write("        <input type=\"text\" name=\"searchValue\" placeholder=\"Search\"/>\n");
      out.write("        <input type=\"submit\" class=\"btn btn-outline-info btn-sm\" value=\"Search for a list\"/>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <ul>\n");
      out.write("    ");

        ArrayList<String> path = (ArrayList<String>) request.getAttribute("PATH");
        int i = 0;
        for (String listName : path){
            if (i != path.size() - 1){
    
      out.write("\n");
      out.write("                <li class=\"inline-list\"><a href=\"list.html?listName=");
      out.print(listName);
      out.write('"');
      out.write('>');
      out.print(listName);
      out.write("</a></li>\n");
      out.write("                <li class=\"inline-list\"><p> -> </p></li>\n");
      out.write("            ");
} else{
      out.write("\n");
      out.write("                <li class=\"inline-list\"><a href=\"list.html?listName=");
      out.print(listName);
      out.write('"');
      out.write('>');
      out.print(listName);
      out.write("</a></li>\n");
      out.write("            ");
 } i++; 
      out.write("\n");
      out.write("\n");
      out.write("            ");
}
    
      out.write("\n");
      out.write("    </ul>\n");
      out.write("    <h2> ");
      out.print((String) request.getAttribute("listName"));
      out.write(" </h2>\n");
      out.write("    <ul>\n");
      out.write("        ");

            for (Object item : (LinkedList<Object>) request.getAttribute("items")){
                if (item instanceof TodoList){
                    TodoList tdl = (TodoList) item;
        
      out.write("\n");
      out.write("        <li><form class=\"inline-list align-middle\" method=\"POST\" action=\"edit.jsp\"><input type=\"hidden\" name=\"type\" value=\"editList\" /><input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" /><input type=\"hidden\" name=\"listToEdit\" value=\"");
      out.print(tdl.getListName());
      out.write("\" /><input class=\"btn btn-outline-dark btn-sm\" type=\"submit\" value=\"✏️\"></form><a href=\"list.html?listName=");
      out.print(tdl.getListName());
      out.write("\" class=\"inline-list\">");
      out.print(tdl.getListName());
      out.write("</a><form class=\"inline-list align-middle\" method=\"POST\" action=\"/updateList.html\"><input type=\"hidden\" name=\"action\" value=\"removeList\" /><input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" /><input type=\"hidden\" name=\"listToRemove\" value=\"");
      out.print(tdl.getListName());
      out.write("\" /><input class=\"btn btn-outline-danger btn-sm\" type=\"submit\" value=\"❌\"></form></li>\n");
      out.write("        ");
  }
            else if (item instanceof Item){
                Item objItem = (Item) item;
        
      out.write("\n");
      out.write("        <li><form class=\"inline-list align-middle\" method=\"POST\" action=\"edit.jsp\" class=\"inline-list\"><input type=\"hidden\" name=\"type\" value=\"editItem\" /><input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" /><input type=\"hidden\" name=\"itemToEdit\" value=\"");
      out.print(item);
      out.write("\" /><input type=\"hidden\" name=\"origText\" value=\"");
      out.print(objItem.getText());
      out.write("\" /><input type=\"hidden\" name=\"origUrl\" value=\"");
      out.print(objItem.getUrl());
      out.write("\" /><input type=\"hidden\" name=\"origImg\" value=\"");
      out.print(objItem.getImage());
      out.write("\" /><input class=\"btn btn-outline-dark btn-sm\" type=\"submit\" value=\"✏️\"></form>\n");
      out.write("            <a href=\"");
      out.print(objItem.getUrl());
      out.write("\"><img src=\"");
      out.print(objItem.getImage());
      out.write("\" alt=\"");
      out.print(objItem.getImage());
      out.write("\" class=\"rounded\" width=\"50\" height=\"50\" /></a>");
      out.print(objItem.getText());
      out.write("\n");
      out.write("        <form class=\"inline-list align-middle\" method=\"POST\" action=\"/updateItem.html\" class=\"inline-list\"><input type=\"hidden\" name=\"action\" value=\"removeItem\" /><input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" /><input type=\"hidden\" name=\"origText\" value=\"");
      out.print(objItem.getText() );
      out.write("\" /><input type=\"hidden\" name=\"origUrl\" value=\"");
      out.print(objItem.getUrl() );
      out.write("\" /><input type=\"hidden\" name=\"origImg\" value=\"");
      out.print(objItem.getImage() );
      out.write("\" /><input class=\"btn btn-outline-danger btn-sm\" type=\"submit\" value=\"❌\"></form></li>\n");
      out.write("        ");
 }
        else{
        
      out.write("\n");
      out.write("        <li><form class=\"inline-list align-middle\" method=\"POST\" action=\"edit.jsp\" class=\"inline-list\"><input type=\"hidden\" name=\"type\" value=\"editItem\" /><input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" /><input type=\"hidden\" name=\"itemToEdit\" value=\"");
      out.print(item.toString());
      out.write("\" /><input class=\"btn btn-outline-dark btn-sm\" type=\"submit\" value=\"✏️\"></form>");
      out.print(item.toString());
      out.write("&nbsp;&nbsp;<form class=\"inline-list align-middle\" method=\"POST\" action=\"/updateItem.html\" class=\"inline-list\"><input type=\"hidden\" name=\"action\" value=\"removeItem\" /><input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" /><input type=\"hidden\" name=\"itemToRemove\" value=\"");
      out.print(item.toString());
      out.write("\" /><input class=\"btn btn-outline-danger btn-sm\" type=\"submit\" value=\"❌\"></form></li>\n");
      out.write("        ");
  } 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<form method=\"POST\" action=\"/updateList.html\">\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"addList\" />\n");
      out.write("    <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" />\n");
      out.write("    <input type=\"text\" name=\"newListName\" placeholder=\"Add list\"/>\n");
      out.write("    <input type=\"submit\" class=\"btn btn-outline-success btn-sm\" value=\"Add List\"/>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<form method=\"POST\" action=\"/updateItem.html\">\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"addItem\" />\n");
      out.write("    <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(request.getAttribute("listName") );
      out.write("\" />\n");
      out.write("    <input type=\"text\" name=\"itemText\" placeholder=\"Add text\"/>\n");
      out.write("    <input type=\"url\" name=\"itemUrl\" placeholder=\"Add url\"/>\n");
      out.write("    <input type=\"url\" name=\"itemImage\" placeholder=\"Add image (url)\"/>\n");
      out.write("    <input type=\"submit\" class=\"btn btn-outline-success btn-sm\" value=\"Add item\"/>\n");
      out.write("</form>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
